name: "Run E2E Test"

on: ["pull_request"]

jobs:
  run-unit-test:
    name: "Run E2E Test"
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres-alpine
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: SomeHashedPassword
          POSTGRESQL_DATABASE: ignite
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm test:e2e
        env:
          JWT_SECRET: secrete
          NODE_END: development
          PORT: 3333
          DATABASE_URL: "postgresql://postgres:SomeHashedPassword@localhost:5432/ignite?schema=tests"
