name: "Run E2E Test"

on: ["pull_request"]

jobs:
  run-unit-test:
    name: "Run E2E Test"
    runs-on: ubuntu-latest

    steps:
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: ignite
          postgresql user: postgres
          postgresql password: SomeHashedPassword
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm run test:e2e
        env:
          JWT_SECRET: secrete
          NODE_END: development
          PORT: 3333
          DATABASE_URL: "postgresql://postgres:SomeHashedPassword@localhost:5432/ignite?schema=tests"
