name: "Run E2E Test"

on: ["pull_request"]

env:
  JWT_SECRET: asjklfhklhfh23489uaensdmacxjbncs
  NODE_ENV: development
  PORT: 3333
  DATABASE_URL: "postgresql://postgres:SomeHashedPassword@localhost:5432/ignite?schema=tests"

jobs:
  run-unit-test:
    name: "Run E2E Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        env:
          JWT_SECRET: ${{ env.JWT_SECRET }}
          NODE_ENV: ${{ env.NODE_ENV }}
          PORT: ${{ env.PORT }}
          DATABASE_URL: ${{ env.DATABASE_URL }}
        with:
          node-version: 18
          cache: "npm"

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: ignite
          postgresql user: postgres
          postgresql password: SomeHashedPassword
      - run: |
          echo "Starting test..."
          echo "This is a node_env secret value: $NODE_ENV"
      - run: npm ci
      - run: npm run test:e2e
